# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ihuoOioZ8x6EkEcoM9pc5mbMwQv/jvbs/3VqSCxhT6tkKF97/jvzLqrlNylsCBfrSa4tncnZIxcubwTwCxmK9bju2PCzGnP2B/Mt26bjCWybC3z+xDbr7Hxd3Dh0IM/noMqDrKBQwPa0Jd9VUnCvteEU/TxYrcBLdgrX0zeVsdY1HxtezAw+v+HG0uZt71OlfJ1/PIJs/0iaPxNGmBt+QojeuAXBDuMl20zZdaxhUPg/JfynqTipP0eGmdEnAMwpreFB0BrL7BJUjNRMy4uIkFU5lp7r5OeLz3Pm/igNceHYW0N4uVI4RF46K60pmCLexfDfyNuMr4JhJHxoQCoSt3HizLbOtXN77qMWHw73dXi+5aaY97P8gl5K7LwlyLOEmXYT2+HuB2mhBv/SRjAwLjWjDO2vefQpKOdEs++xqODHWcSW/9KNqrQ8rfi9acMxY1NOBzHtSJ0xm0pnvhBrSS3gctC6KNHMjuG+UnmbzltGA8jDEsksw5qYRdPL/qUeXIH0NKVe6h3qFwWjT2ICclsPv0+OfMJ5KmftVranfhr5rfRWbgZV3qx6EhqphBcTX2x0Lm6lCSGKj0LOJkGWrz5KUJNMbF/irpIY1BEr6k7J+F+SlB9bNEUJI8Ru7tyFBCk6CSl5FFeTasrd/b1hQmkwv+VyO7h1Qg1/ltFamfU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
