travis:
  secure:
    BINSTAR_TOKEN: fd4iEDYM5whZ79MvwlDisRAYng9Y3EyMr7oyg2TggvvnHWs3FWgoSK9+/8YEDMHrRD5Q+BQgzqcP9Ux+ujPpIFkra8q89NsYSXws5ghlEmuPjuIzIVJLbtDuvyDTCXGijUryvxGK3qvEq60rd8lsP2Q4L9DCMvzAZ8eVDjTrwnqtZx9u5X5ySegTqkFZU/AOs/ZLZUKW3Q6TbR/NQu/TqjW4gneXLaGujr6PmjgVDovFMTFSTLkmNV9dmeRFmfAhZwAdCcddSHK57FYmGbwpkEq2bJd/sHFARom7EGk7e0juUIVwDbjWuF7Js3swviPRIUpVKKVSlS/poiP9s8cCGPsMJXm+6WTSnFnGPIRbBF4YQVbDlAHRh1G5sVjo6LVy8PvTs5kjQS7o3PTk9Xs50x2agpoCsDtdKZ0n3ttf6qJI5r+t9WgbjDNw8ioolOpc2SMqU+bGMhxi/9AFGCOc+tT2+VWTmmdmbLkP2TAD/ua3aKCjsMUGI4lIEvKAn2qT5vqX3YmYvDfjLqM6HlnXdw98P6aT87w3qm0oFlUh7FkelZke06TKunBhfRERNLCMIagtIXjQIV+hziFppVpLw5QWvCQyeAvlK8O3B5RIqpF1TvWYsMsCUhCCHdtjYYnKuQNBnOuiFhgNy+LMhZ5dB9M9uiyjv9cR3CNENdt2nbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
